# Generated by Django 5.0.2 on 2024-02-23 23:54

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
